/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  StPayment as StPayment
} from './components/st-payment/st-payment';

declare global {
  interface HTMLStPaymentElement extends StPayment, HTMLElement {
  }
  var HTMLStPaymentElement: {
    prototype: HTMLStPaymentElement;
    new (): HTMLStPaymentElement;
  };
  interface HTMLElementTagNameMap {
    "st-payment": HTMLStPaymentElement;
  }
  interface ElementTagNameMap {
    "st-payment": HTMLStPaymentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "st-payment": JSXElements.StPaymentAttributes;
    }
  }
  namespace JSXElements {
    export interface StPaymentAttributes extends HTMLAttributes {
      callback?: any;
      details?: any;
      methodData?: any;
      options?: any;
    }
  }
}

